#!/bin/bash
# =============================================================================
# sbatch_phase0_phase1_hpc.sh
#
# Phase 0 + Phase 1 (HPC portion) of the continuation plan.
# Bundles every GPU / long-CV job that's too heavy for a laptop into one SLURM
# submission targeted at Yale Bouchet (cpsc4770_ym466).
#
# Submit with:
#     cd /home/cpsc4770_ym466/project_cpsc4770/cpsc4770_ym466/LLM-Reasoning-Trace-Topology
#     sbatch scripts/sbatch_phase0_phase1_hpc.sh
#
# What this job does (in order):
#   1. Rebuild data/step_embeddings/*.npz under the FIXED parser-vocab mapping
#      (REVISE no longer silently maps to PAD).
#   2. StepTF pooled (5-fold CV, single seed) — the canonical structural-neural number.
#   3. StepTF per-dataset (8 separate runs).
#   4. DeBERTa pooled.
#   5. DeBERTa per-dataset (8 runs).
#   6. Hybrid stacking, single-seed per call, for seeds {42, 1, 2, 3} → 4 JSONs.
#      The existing results/month2/hybrid_pooled.json was generated by an
#      older buggy code path that evaluated on the TRAIN split (n=25,512 =
#      6378 × 4); current src/modeling/hybrid.py is correct, this just runs it.
#   7. PRR backfill on every newly produced OOF .npz.
#
# Outputs land under results/month2_v2/ so results/month2/ stays as the
# reference baseline for diffs.
#
# Estimated wall-clock on 1× A100: ~4-7 hr; 12 hr requested has headroom.
# =============================================================================

# ---------- Hard-coded absolute paths (so --output/--error don't depend on submit dir) ----------
#SBATCH --job-name=trace_uq_p0p1
#SBATCH --partition=gpu_rtx6000
#SBATCH --gpus=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=9:00:00
#SBATCH --chdir=/home/cpsc4770_ym466/project_cpsc4770/cpsc4770_ym466/LLM-Reasoning-Trace-Topology
#SBATCH --output=/home/cpsc4770_ym466/project_cpsc4770/cpsc4770_ym466/LLM-Reasoning-Trace-Topology/logs/p0p1_%j.out
#SBATCH --error=/home/cpsc4770_ym466/project_cpsc4770/cpsc4770_ym466/LLM-Reasoning-Trace-Topology/logs/p0p1_%j.err
#SBATCH --mail-type=ALL
# If your account / partition / GPU type differs, override at submit time:
#   sbatch --partition=gpu_devel --gres=gpu:a100:1 --time=06:00:00 \
#          scripts/sbatch_phase0_phase1_hpc.sh

# ---------- Debug / error-trap prelude (helps diagnose silent failures) ----------
# NOTE: we use -e + pipefail but NOT -u (nounset) because conda's shell hook
# references several unset variables as part of normal operation. We also
# briefly disable -e around the activation block so failing-but-recoverable
# steps (e.g. probing which conda module exists) don't kill the job.
set -Eeo pipefail
trap 'ec=$?; echo "==== FAILED at line $LINENO (exit $ec): $BASH_COMMAND" >&2; exit $ec' ERR
# Uncomment the next line if the script fails silently again — floods the log with every command:
#set -x

# =============================================================================
# CLUSTER / ENV CONFIGURATION  (override at submit time via env vars if needed)
# =============================================================================
PROJECT_DIR="${PROJECT_DIR:-/home/cpsc4770_ym466/project_cpsc4770/cpsc4770_ym466/LLM-Reasoning-Trace-Topology}"
CONDA_ENV="${CONDA_ENV:-torch311}"      # name of the conda env on Bouchet; override via sbatch --export=...
HF_HOME_OVERRIDE="${HF_HOME:-$PROJECT_DIR/.cache/huggingface}"

cd "$PROJECT_DIR" || { echo "FATAL: cd $PROJECT_DIR failed"; exit 1; }
mkdir -p logs results/month2_v2 data/step_embeddings .cache/huggingface

echo "=========================================================================="
echo "Job:         ${SLURM_JOB_NAME:-?}  (id=${SLURM_JOB_ID:-?})"
echo "Started:     $(date)"
echo "Node:        $(hostname)"
echo "Submit dir:  ${SLURM_SUBMIT_DIR:-?}"
echo "PWD:         $PWD"
echo "PROJECT_DIR: $PROJECT_DIR"
echo "CONDA_ENV:   $CONDA_ENV"
echo "PATH:        $PATH"
echo "GPUs:        $(nvidia-smi -L 2>/dev/null || echo 'NONE DETECTED')"
echo "=========================================================================="

# =============================================================================
# Activate environment — the condabin directory is already on $PATH via the
# user's login profile (see PATH printed above), so we do NOT need to source
# /etc/profile.d/{modules,lmod}.sh or call 'module load miniconda'. Those system
# scripts contain zsh-oriented snippets (e.g. 'compinit -c') that return 127
# in bash and would trigger our ERR trap.
# =============================================================================
echo ""
echo "=== Activating conda env '$CONDA_ENV' ==="

# IMPORTANT: 'trap - ERR' actually disables the ERR trap in bash. 'set +e'
# alone does NOT — the trap fires on non-zero exits regardless of -e. The
# conda shell hook + 'conda activate' legitimately produce non-zero exits
# along informational paths; we silence the trap here and re-install it
# after activation completes.
trap - ERR
set +e

module load miniconda || { echo "FATAL: 'module load miniconda' failed"; exit 2; }

echo "  conda binary: $(command -v conda)"


echo "  conda envs available:"
conda env list 2>&1 | sed 's/^/    /' | head -20

conda activate "$CONDA_ENV"
act_rc=$?
if [ $act_rc -ne 0 ]; then
    echo "FATAL: 'conda activate $CONDA_ENV' failed (rc=$act_rc). Env list above."
    exit 4
fi
echo "  Active env: ${CONDA_DEFAULT_ENV:-?}"

if ! command -v python >/dev/null 2>&1; then
    echo "FATAL: python still not on PATH after 'conda activate $CONDA_ENV'"
    exit 5
fi
echo "  Python:     $(command -v python)  $(python -V 2>&1)"

# Verify torch imports and CUDA is visible BEFORE re-enabling trap
if ! python -c 'import torch; print("  Torch:     ", torch.__version__, " cuda=", torch.cuda.is_available())'; then
    echo "FATAL: 'import torch' failed in env '$CONDA_ENV' — is torch installed there?"
    exit 6
fi

# Re-enable strict error handling for the science workload below
set -e
trap 'ec=$?; echo "==== FAILED at line $LINENO (exit $ec): $BASH_COMMAND" >&2; exit $ec' ERR

# =============================================================================
# Project paths and env vars
# =============================================================================
export PYTHONPATH="$PROJECT_DIR"
export HF_HOME="$HF_HOME_OVERRIDE"
mkdir -p "$HF_HOME"
echo "PYTHONPATH: $PYTHONPATH"
echo "HF_HOME:    $HF_HOME"

# Source project .env (HF_TOKEN, DEEPSEEK_API_KEY, etc.) without overriding existing vars
if [ -f "$PROJECT_DIR/.env" ]; then
    echo "Loading .env from $PROJECT_DIR/.env"
    set -a; source "$PROJECT_DIR/.env"; set +a
fi

# =============================================================================
# Lightweight dependency check (don't try to install — that's a setup step)
# =============================================================================
echo ""
echo "=== Dependency check ==="
python - <<'PYCHECK' || { echo "FATAL: missing dependency above; activate the right conda env"; exit 3; }
import importlib, sys
required = ["torch", "numpy", "pandas", "sklearn", "tqdm",
            "sentence_transformers", "transformers", "sentencepiece"]
optional = ["xgboost"]
missing = []
for m in required:
    try: importlib.import_module(m); print(f"  OK   {m}")
    except Exception as e: print(f"  MISS {m}: {e}"); missing.append(m)
for m in optional:
    try: importlib.import_module(m); print(f"  OK   {m} (optional)")
    except Exception: print(f"  WARN {m} (optional, hybrid xgb meta will be skipped)")
sys.exit(1 if missing else 0)
PYCHECK

DATASETS=(math500_qwen7b math500_llama8b
          gsm8k_qwen7b gsm8k_llama8b
          gpqa_diamond_qwen7b gpqa_diamond_llama8b
          arc_challenge_qwen7b arc_challenge_llama8b)

# =============================================================================
# 1. Rebuild step embeddings under the FIXED parser-vocab mapping
# =============================================================================
echo ""
echo "=========================================================================="
echo "Step 1: REBUILD step embeddings (parser-vocab fix; REVISE no longer PAD)"
echo "=========================================================================="
echo "Wiping stale .npz so the fixed parser fully repopulates step_types..."
rm -f data/step_embeddings/*.npz
python scripts/build_step_embeddings.py --all --batch-size 256 || exit 11
ls -la data/step_embeddings/

# Sanity: at least one non-PAD step type should now appear in every .npz
echo ""
echo "Verifying non-PAD step types post-rebuild..."
python - <<'PYVERIFY' || exit 12
import numpy as np, glob, sys
ok = True
for p in sorted(glob.glob('data/step_embeddings/*.npz')):
    z = np.load(p, allow_pickle=True)
    types = z['step_types']
    flat = np.concatenate([t for t in types if len(t)]) if len(types) else np.array([])
    uniq = sorted(set(int(x) for x in flat))
    print(f"  {p}: step_types unique = {uniq}")
    if uniq == [0]:
        print(f"  ERROR: {p} only contains PAD — bug not fixed?")
        ok = False
sys.exit(0 if ok else 1)
PYVERIFY

# =============================================================================
# 2. Step Transformer — pooled
# =============================================================================
echo ""
echo "=========================================================================="
echo "Step 2: StepTF pooled (5-fold CV, single seed=42)"
echo "=========================================================================="
python src/modeling/step_transformer.py \
    --npz-glob "data/step_embeddings/*.npz" \
    --output   results/month2_v2/step_transformer_pooled.json \
    --epochs 15 --batch-size 32 --lr 3e-4 --seed 42 || exit 21

# =============================================================================
# 3. Step Transformer — per-dataset
# =============================================================================
echo ""
echo "=========================================================================="
echo "Step 3: StepTF per-dataset (8 separate single-dataset runs)"
echo "=========================================================================="
for DS in "${DATASETS[@]}"; do
    NPZ="data/step_embeddings/${DS}.npz"
    OUT="results/month2_v2/step_transformer_${DS}.json"
    if [ ! -f "$NPZ" ]; then
        echo "  -> $DS  (npz missing, skip)"; continue
    fi
    if [ -f "$OUT" ]; then
        echo "  -> $DS  (already done, skip)"; continue
    fi
    echo "  -> $DS"
    python src/modeling/step_transformer.py \
        --npz "$NPZ" \
        --output "$OUT" \
        --epochs 15 --batch-size 32 --lr 3e-4 --seed 42 \
        || echo "  WARNING: StepTF failed on $DS"
done

# =============================================================================
# 4. DeBERTa — pooled
# =============================================================================
echo ""
echo "=========================================================================="
echo "Step 4: DeBERTa pooled (3 epochs, 5-fold CV, last 512 tokens)"
echo "=========================================================================="
if [ -f results/month2_v2/deberta_pooled.json ]; then
    echo "  (already done, skip)"
else
    python src/modeling/deberta_baseline.py \
        --traces-glob "data/traces/*_traces.jsonl" \
        --output results/month2_v2/deberta_pooled.json \
        --epochs 3 --batch-size 8 --lr 2e-5 --seed 42 || exit 41
fi

# =============================================================================
# 5. DeBERTa — per-dataset
# =============================================================================
echo ""
echo "=========================================================================="
echo "Step 5: DeBERTa per-dataset (8 separate single-dataset runs)"
echo "=========================================================================="
for DS in "${DATASETS[@]}"; do
    GLOB="data/traces/${DS}_traces.jsonl"
    OUT="results/month2_v2/deberta_${DS}.json"
    if [ ! -f "$GLOB" ]; then
        echo "  -> $DS  (traces missing, skip)"; continue
    fi
    if [ -f "$OUT" ]; then
        echo "  -> $DS  (already done, skip)"; continue
    fi
    echo "  -> $DS"
    python src/modeling/deberta_baseline.py \
        --traces-glob "$GLOB" \
        --output "$OUT" \
        --epochs 3 --batch-size 8 --lr 2e-5 --seed 42 \
        || echo "  WARNING: DeBERTa failed on $DS"
done

# =============================================================================
# 6. Hybrid honest single-seed × 4 seeds
# =============================================================================
echo ""
echo "=========================================================================="
echo "Step 6: Hybrid stacking, honest single-seed × 4 seeds"
echo "=========================================================================="
DEBERTA_OOF="results/month2_v2/deberta_pooled_oof.npz"
STEP_OOF="results/month2_v2/step_transformer_pooled_oof.npz"
if [ ! -f "$DEBERTA_OOF" ] || [ ! -f "$STEP_OOF" ]; then
    echo "WARNING: Pooled OOF .npz missing; skipping hybrid"
else
    for SEED in 42 1 2 3; do
        OUT="results/month2_v2/hybrid_pooled_seed${SEED}.json"
        if [ -f "$OUT" ]; then
            echo "  -> seed=$SEED  (already done, skip)"; continue
        fi
        echo "  -> seed=$SEED"
        python src/modeling/hybrid.py \
            --deberta-oof   "$DEBERTA_OOF" \
            --step-oof      "$STEP_OOF" \
            --features-glob "data/features/*_features_rec.csv" \
            --output        "$OUT" \
            --clf all --seed "$SEED" \
            || echo "  WARNING: hybrid failed at seed=$SEED"
    done
fi

# =============================================================================
# 7. PRR backfill on every new OOF
# =============================================================================
echo ""
echo "=========================================================================="
echo "Step 7: PRR backfill on results/month2_v2/*_oof.npz"
echo "=========================================================================="
python scripts/backfill_prr.py --glob "results/month2_v2/*_oof.npz" || true

# =============================================================================
# Done
# =============================================================================
echo ""
echo "=========================================================================="
echo "Finished at $(date)"
echo "=========================================================================="
ls -la results/month2_v2/
